import Foundation

/// The registry as a value, so export, import and the tests do not touch the global.
public struct TokenRegistry: Sendable, Equatable {
    public var colors: [ColorToken]
    public var dimensions: [DimensionToken]
    public var typography: [TypographyToken]

    public init(colors: [ColorToken], dimensions: [DimensionToken], typography: [TypographyToken]) {
        self.colors = colors
        self.dimensions = dimensions
        self.typography = typography
    }

    public static let current = TokenRegistry(colors: TokenValues.colors, dimensions: TokenValues.dimensions, typography: TokenValues.typography)
}

/// Design Tokens Community Group format (current draft, www.designtokens.org/TR/drafts/format):
/// colour `$value` is `{ colorSpace, components, hex }`, dimension is `{ value, unit: "px" }`, typography is composite.
/// Iter-specific data (dark value, system alias, text style, design, monospaced digits) lives under
/// `$extensions["com.dwjames.iter"]`.
public enum TokenCodec {
    public static let extensionKey = "com.dwjames.iter"

    // MARK: Export

    public static func exportJSON(_ registry: TokenRegistry) -> String {
        var root = Group()
        for t in registry.colors { root.insert(t.name.split(separator: "/").map(String.init), colorJSON(t)) }
        for t in registry.dimensions { root.insert(t.name.split(separator: "/").map(String.init), dimensionJSON(t)) }
        for t in registry.typography { root.insert(t.name.split(separator: "/").map(String.init), typographyJSON(t)) }
        var pairs: [(key: String, value: OrderedJSON)] = [
            ("$description", .string("Iter design tokens. Generated by iter-tokens export from TokenValues.swift; edit and run iter-tokens import to bring changes back. Dark values and system colour aliases are under $extensions[\"com.dwjames.iter\"]."))
        ]
        pairs += root.json().pairs ?? []
        return OrderedJSON.object(pairs).serialized()
    }

    private struct Group {
        var children: [(key: String, node: Node)] = []
        enum Node { case group(Group), leaf(OrderedJSON) }

        mutating func insert(_ path: [String], _ leaf: OrderedJSON) {
            guard let first = path.first else { return }
            if path.count == 1 { children.append((first, .leaf(leaf))); return }
            if let idx = children.firstIndex(where: { $0.key == first }), case .group(var g) = children[idx].node {
                g.insert(Array(path.dropFirst()), leaf)
                children[idx].node = .group(g)
            } else {
                var g = Group()
                g.insert(Array(path.dropFirst()), leaf)
                children.append((first, .group(g)))
            }
        }

        func json() -> OrderedJSON {
            .object(children.map { c in
                switch c.node {
                case .group(let g): (c.key, g.json())
                case .leaf(let j): (c.key, j)
                }
            })
        }
    }

    private static func ext(_ pairs: [(key: String, value: OrderedJSON)]) -> OrderedJSON {
        .object([(extensionKey, .object(pairs))])
    }

    private static func component(_ v: Int) -> Double { (Double(v) / 255 * 10_000).rounded() / 10_000 }

    private static func colorJSON(_ t: ColorToken) -> OrderedJSON {
        let c = t.lightRGB
        var x: [(key: String, value: OrderedJSON)] = [("dark", .string(t.darkRGB.hex))]
        if let s = t.systemAlias { x.append(("system", .string(s))) }
        return .object([
            ("$type", .string("color")),
            ("$value", .object([
                ("colorSpace", .string("srgb")),
                ("components", .array([component(c.red), component(c.green), component(c.blue)].map { .number($0) })),
                ("hex", .string(c.hex.lowercased())),
            ])),
            ("$description", .string(t.description)),
            ("$extensions", ext(x)),
        ])
    }

    private static func dimensionJSON(_ t: DimensionToken) -> OrderedJSON {
        .object([
            ("$type", .string("dimension")),
            ("$value", .object([("value", .number(t.points)), ("unit", .string("px"))])),
            ("$description", .string(t.description)),
        ])
    }

    private static func typographyJSON(_ t: TypographyToken) -> OrderedJSON {
        .object([
            ("$type", .string("typography")),
            ("$value", .object([
                ("fontFamily", .string(t.design.familyName)),
                ("fontSize", .object([("value", .number(t.style.referencePoints)), ("unit", .string("px"))])),
                ("fontWeight", .number(Double(t.weight.number))),
            ])),
            ("$description", .string(t.description)),
            ("$extensions", ext([
                ("textStyle", .string(t.style.rawValue)),
                ("design", .string(t.design.rawValue)),
                ("monospacedDigits", .bool(t.monospacedDigits)),
            ])),
        ])
    }

    // MARK: Import

    public static func importJSON(_ text: String) throws -> TokenRegistry {
        let root = try OrderedJSON.parse(text)
        var reg = TokenRegistry(colors: [], dimensions: [], typography: [])
        try walk(root, path: [], into: &reg)
        return reg
    }

    private static func walk(_ node: OrderedJSON, path: [String], into reg: inout TokenRegistry) throws {
        guard let pairs = node.pairs else { return }
        if node["$value"] != nil {
            let name = path.joined(separator: "/")
            switch node["$type"]?.stringValue {
            case "color": reg.colors.append(try parseColor(node, name))
            case "dimension": reg.dimensions.append(try parseDimension(node, name))
            case "typography": reg.typography.append(try parseTypography(node, name))
            default: throw TokenError("Token \(name) has unsupported $type \(node["$type"]?.stringValue ?? "(none)")")
            }
            return
        }
        for p in pairs where !p.key.hasPrefix("$") { try walk(p.value, path: path + [p.key], into: &reg) }
    }

    private static func iterExtension(_ node: OrderedJSON) -> OrderedJSON? { node["$extensions"]?[extensionKey] }

    private static func parseHex(_ v: OrderedJSON, _ name: String) throws -> RGB {
        if let hex = v["hex"]?.stringValue, let rgb = RGB(hex: hex.uppercased()) { return rgb }
        if case .array(let comps)? = v["components"], comps.count == 3 {
            let n = comps.compactMap(\.numberValue).map { Int(($0 * 255).rounded()) }
            if n.count == 3 { return RGB(red: n[0], green: n[1], blue: n[2]) }
        }
        throw TokenError("Token \(name) has no usable colour value")
    }

    private static func parseColor(_ node: OrderedJSON, _ name: String) throws -> ColorToken {
        guard let value = node["$value"] else { throw TokenError("Token \(name) has no $value") }
        let light = try parseHex(value, name)
        var dark = light
        if let d = iterExtension(node)?["dark"]?.stringValue {
            guard let rgb = RGB(hex: d.uppercased()) else { throw TokenError("Token \(name) has a bad dark hex \(d)") }
            dark = rgb
        }
        return ColorToken(name, light: light.hex, dark: dark.hex, system: iterExtension(node)?["system"]?.stringValue,
                          node["$description"]?.stringValue ?? "")
    }

    private static func points(_ v: OrderedJSON?, _ name: String) throws -> Double {
        guard let v, let n = v["value"]?.numberValue else { throw TokenError("Token \(name) has no dimension value") }
        switch v["unit"]?.stringValue {
        case "px", nil: return n
        case "rem": return n * 16
        case let u?: throw TokenError("Token \(name) has unsupported unit \(u)")
        }
    }

    private static func parseDimension(_ node: OrderedJSON, _ name: String) throws -> DimensionToken {
        DimensionToken(name, try points(node["$value"], name), node["$description"]?.stringValue ?? "")
    }

    private static func parseTypography(_ node: OrderedJSON, _ name: String) throws -> TypographyToken {
        guard let x = iterExtension(node), let styleRaw = x["textStyle"]?.stringValue, let style = TextStyleName(rawValue: styleRaw) else {
            throw TokenError("Typography token \(name) needs $extensions.\(extensionKey).textStyle")
        }
        let design = x["design"]?.stringValue.flatMap(FontDesignName.init(rawValue:)) ?? .standard
        let number = Int(node["$value"]?["fontWeight"]?.numberValue ?? 400)
        guard let weight = FontWeightName(number: number) else { throw TokenError("Typography token \(name) has unsupported fontWeight \(number)") }
        return TypographyToken(name, style, weight, design, monoDigits: x["monospacedDigits"]?.boolValue ?? false,
                               node["$description"]?.stringValue ?? "")
    }

    // MARK: Swift source

    public static func swiftSource(_ registry: TokenRegistry) -> String {
        func q(_ s: String) -> String { OrderedJSON.quote(s) }
        var out = """
        // Generated by `iter-tokens import` from Design/tokens.json. Safe to hand-edit: `iter-tokens export` writes
        // tokens.json and the asset-catalog colour sets from this file, and the tests check that this file is exactly what
        // the generator would write (so keep the one-token-per-line layout, or run `scripts/tokens.sh` after editing).
        //
        // Colours are #RRGGBB for sRGB. A `system:` alias means the app uses that system colour at run time and the hex
        // pair is only its resolved reference (light #ECECEC window, dark #1E1E1E window).

        public enum TokenValues {
            public static let colors: [ColorToken] = [

        """
        for t in registry.colors {
            let sys = t.systemAlias.map { ", system: \(q($0))" } ?? ""
            out += "        ColorToken(\(q(t.name)), light: \(q(t.light)), dark: \(q(t.dark))\(sys), \(q(t.description))),\n"
        }
        out += "    ]\n\n    public static let dimensions: [DimensionToken] = [\n"
        for t in registry.dimensions {
            out += "        DimensionToken(\(q(t.name)), \(OrderedJSON.formatNumber(t.points)), \(q(t.description))),\n"
        }
        out += "    ]\n\n    public static let typography: [TypographyToken] = [\n"
        for t in registry.typography {
            out += "        TypographyToken(\(q(t.name)), .\(t.style.rawValue), .\(t.weight.rawValue), .\(t.design.rawValue), monoDigits: \(t.monospacedDigits), \(q(t.description))),\n"
        }
        out += "    ]\n}\n"
        return out
    }

    // MARK: Asset catalog

    /// Writes `Tokens/<name>.colorset` for every colour and `AccentColor.colorset` from `accent/primary`.
    /// The `Tokens` folder is owned by this tool and rewritten from scratch.
    public static func writeAssets(_ registry: TokenRegistry, to catalog: URL) throws {
        let fm = FileManager.default
        let tokens = catalog.appendingPathComponent("Tokens", isDirectory: true)
        if fm.fileExists(atPath: tokens.path) { try fm.removeItem(at: tokens) }
        try fm.createDirectory(at: tokens, withIntermediateDirectories: true)
        try write(OrderedJSON.object([("info", infoJSON)]).serialized(), to: tokens.appendingPathComponent("Contents.json"))
        for t in registry.colors {
            let dir = tokens.appendingPathComponent(assetName(t.name) + ".colorset", isDirectory: true)
            try fm.createDirectory(at: dir, withIntermediateDirectories: true)
            try write(colorsetJSON(t).serialized(), to: dir.appendingPathComponent("Contents.json"))
        }
        if let accent = registry.colors.first(where: { $0.name == "accent/primary" }) {
            let dir = catalog.appendingPathComponent("AccentColor.colorset", isDirectory: true)
            try fm.createDirectory(at: dir, withIntermediateDirectories: true)
            try write(colorsetJSON(accent).serialized(), to: dir.appendingPathComponent("Contents.json"))
        }
    }

    /// Asset name used by `Color("...")` lookups: path separators become dashes.
    public static func assetName(_ token: String) -> String { token.replacingOccurrences(of: "/", with: "-") }

    private static let infoJSON: OrderedJSON = .object([("author", .string("iter-tokens")), ("version", .number(1))])

    private static func colorsetJSON(_ t: ColorToken) -> OrderedJSON {
        func entry(_ c: RGB, dark: Bool) -> OrderedJSON {
            var pairs: [(key: String, value: OrderedJSON)] = []
            if dark {
                pairs.append(("appearances", .array([.object([("appearance", .string("luminosity")), ("value", .string("dark"))])])))
            }
            pairs.append(("color", .object([
                ("color-space", .string("srgb")),
                ("components", .object([
                    ("alpha", .string("1.000")),
                    ("blue", .string(String(format: "0x%02X", c.blue))),
                    ("green", .string(String(format: "0x%02X", c.green))),
                    ("red", .string(String(format: "0x%02X", c.red))),
                ])),
            ])))
            pairs.append(("idiom", .string("universal")))
            return .object(pairs)
        }
        return .object([("colors", .array([entry(t.lightRGB, dark: false), entry(t.darkRGB, dark: true)])), ("info", infoJSON)])
    }

    private static func write(_ text: String, to url: URL) throws {
        try text.write(to: url, atomically: true, encoding: .utf8)
    }
}
