#!/usr/bin/env node
// build-index.mjs - writes Design/paper/INDEX.md (generated): every artboard with name, page, size, theme, covers,
// Paper call estimate (from artboards/calls.json; run calls.mjs first) and bytes.
//   node Design/paper/tools/build-index.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const paperDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
import { PAGES, orderManifest, groupOf } from './lib/order.mjs';
const man = orderManifest(JSON.parse(fs.readFileSync(path.join(paperDir, 'artboards', 'manifest.json'), 'utf8'))); // canonical order: tools/lib/order.mjs
const cp = path.join(paperDir, 'artboards', 'calls.json');
const calls = fs.existsSync(cp) ? JSON.parse(fs.readFileSync(cp, 'utf8')) : { artboards: [], total: null };
const byFile = new Map(calls.artboards.map((a) => [a.file + '.html', a]));
const ORDER = PAGES;
const md = (s) => String(s).replace(/\|/g, '\\|');
const real = man.filter((m) => !m.companionOf), comps = man.filter((m) => m.companionOf);
const kb = (n) => (n / 1024).toFixed(0);
const biggest = man.reduce((a, b) => (b.bytes > a.bytes ? b : a));
let out = `# Iter artboards index\n\nGenerated by \`tools/build-index.mjs\` (order: \`tools/lib/order.mjs\`) from \`artboards/manifest.json\` and \`artboards/calls.json\`. Do not edit.\n\n`;
out += `## Totals\n\n- ${man.length} artboard files: ${real.length} real artboards + ${comps.length} note companions\n- Total size: ${kb(man.reduce((a, m) => a + m.bytes, 0))} KB; largest file: \`${biggest.file}\` (${kb(biggest.bytes)} KB)\n`;
if (calls.total) out += `- Estimated Paper calls (artboards only): ${calls.total.withSavings} with clones/duplicates, ${calls.total.withoutSavings} without\n`;
out += `\n| Page | Artboards | Real | Companions | Calls |\n|---|---|---|---|---|\n`;
for (const page of ORDER) { const it = man.filter((m) => m.page === page); if (!it.length) continue; out += `| ${page} | ${it.length} | ${it.filter((m) => !m.companionOf).length} | ${it.filter((m) => m.companionOf).length} | ${it.reduce((a, m) => a + (byFile.get(m.file)?.callsWithSavings || 0), 0)} |\n`; }
out += '\n';
for (const page of ORDER) {
  const items = man.filter((m) => m.page === page);
  if (!items.length) continue;
  out += `## ${page}\n\n`;
  let lastG = null;
  for (const m of items) {
    const g = groupOf(m).label;
    if (g !== lastG) { out += `${lastG === null ? '' : '\n'}### ${g}\n\n| Artboard | File | Size | Theme | Calls | KB | Covers | Notes |\n|---|---|---|---|---|---|---|---|\n`; lastG = g; }
    const c = byFile.get(m.file);
    out += `| ${md(m.name)} | \`artboards/${m.file}\` | ${m.width}×${m.height} | ${m.theme} | ${c ? c.callsWithSavings : '-'}${c && c.duplicateOf ? ' (dup)' : ''} | ${(m.bytes / 1024).toFixed(0)} | ${md((m.covers || []).join('; '))} | ${md((m.notes || []).join('; '))} |\n`;
  }
  out += '\n';
}
fs.writeFileSync(path.join(paperDir, 'INDEX.md'), out);
console.log(`INDEX.md: ${man.length} artboards`);
