#!/usr/bin/env node
// layout.mjs - world positions for every artboard: artboards/layout.json
//   node Design/paper/tools/layout.mjs
// Per page: rows by section (SCREENS.md section on screen pages, COMPONENTS.md group on Components, one row for Foundations/Flows),
// rows wrap at WRAP px (6000 Foundations/Components, 8000 Screens/Flows); artboards 200px apart, a companion note artboard
// 40px to the right of its artboard; rows 400px apart; each row has a label 120px above its artboards (label box 60px high).
// Positions are top-left in Paper page coordinates (set as `left`/`top` styles in create_artboard). Order: tools/lib/order.mjs.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PAGES, orderManifest, groupOf } from './lib/order.mjs';
const paperDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const man = JSON.parse(fs.readFileSync(path.join(paperDir, 'artboards', 'manifest.json'), 'utf8'));
const WRAP = { Foundations: 6000, Components: 6000, 'Screens (Light)': 8000, 'Screens (Dark)': 8000, Flows: 8000 };
const GAP = 200, COMPANION_GAP = 40, ROW_GAP = 400, LABEL_H = 60, LABEL_OFFSET = 120;
const ordered = orderManifest(man);
const out = { $comment: 'GENERATED by tools/layout.mjs. Top-left world coordinates per page. gaps: 200 between artboards, 40 companion, 400 between rows, label 120px above the row.', gaps: { artboard: GAP, companion: COMPANION_GAP, row: ROW_GAP, labelOffset: LABEL_OFFSET }, pages: {} };
for (const page of PAGES) {
  const items = ordered.filter((e) => e.page === page);
  if (!items.length) continue;
  const wrap = WRAP[page];
  // units: an artboard with its companions
  const units = [];
  for (const e of items) {
    if (e.companionOf) { const u = units.find((x) => x.main.id === e.companionOf); if (u) { u.companions.push(e); continue; } }
    units.push({ main: e, companions: [] });
  }
  const rows = [];
  for (const u of units) {
    const g = groupOf(u.main);
    const w = u.main.width + u.companions.reduce((a, c) => a + COMPANION_GAP + c.width, 0);
    const h = Math.max(u.main.height, ...u.companions.map((c) => c.height));
    let row = rows[rows.length - 1];
    if (!row || row.key !== g.key || (row.width > 0 && row.width + GAP + w > wrap)) {
      const cont = row && row.key === g.key;
      row = { key: g.key, label: cont ? `${g.label} (cont.)` : g.label, units: [], width: 0, height: 0 };
      rows.push(row);
    }
    row.units.push({ u, x: row.width ? row.width + GAP : 0, w, h });
    row.width = (row.width ? row.width + GAP : 0) + w;
    row.height = Math.max(row.height, h);
  }
  let y = 0, worldW = 0;
  const outRows = [];
  for (const r of rows) {
    const labelY = y, top = y + LABEL_OFFSET;
    const placed = [];
    for (const { u, x } of r.units) {
      const place = (e, px) => placed.push({ id: e.id, theme: e.theme, name: e.name, file: e.file, width: e.width, height: e.height, x: px, y: top, ...(e.companionOf ? { companionOf: e.companionOf } : {}) });
      place(u.main, x);
      let cx = x + u.main.width;
      for (const c of u.companions) { cx += COMPANION_GAP; place(c, cx); cx += c.width; }
    }
    outRows.push({ label: r.label, labelBox: { x: 0, y: labelY, width: Math.min(r.width, 1200), height: LABEL_H }, y: top, width: r.width, height: r.height, items: placed });
    worldW = Math.max(worldW, r.width);
    y = top + r.height + ROW_GAP;
  }
  out.pages[page] = { width: worldW, height: y - ROW_GAP, rows: outRows };
}
fs.writeFileSync(path.join(paperDir, 'artboards', 'layout.json'), JSON.stringify(out, null, 1));
for (const [p, v] of Object.entries(out.pages)) console.log(`${p}: ${v.rows.length} rows, world ${v.width} x ${v.height}`);
